### ISSUE TITLE
Demo gradually revealed text broken

### ISSUE THREAD

**Issue by damaskino** [3ter/iMagine#15]
Steps to reproduce:

Select Demo,
Type some stuff, press Enter
Press Escape to return to Menu,
Select Demo again

--> Revealed text looks jumbled now

**Comment by 3ter** [comment]
With 890c618684d14aca2dbb247f72b65bc4bb9c5cf0 this becomes better. Sufficiently better or do we need to adjust the demo further (clearing and sending done when escape is pressed)? I think it's fine for the demo.
