### ISSUE TITLE
Criteria Conditions

### ISSUE THREAD

**Issue by Zet237** [3ter/iMagine#23]
Criteria Conditions work as expected (e.g. cupboard opens on key use, etc. see [Wiki](https://github.com/3ter/iMagine/wiki/Interactives))

- [x] Add dynamic import of JSON Objects (e.g. _cupboard key_)
  - [x] Add Objects to scenes so they can be interacted with
- [ ] Add logic for the verbs `look`, `open`, `use`
  - [ ] The game should behave like the example in the Wiki

**Comment by 3ter** [comment]
@Zet237 What do you think of the following example structure? I just figured that `actions` need `changes/updates` as well.
After the cupboard has been opened some item could be added to the players inventory.
```json
{
    "id": "keyCupboard1",
    "scene": "Lighthouse",
    "name": "old cupboard key",
    "description": "An old key with a square hole in the end, It looks like it belongs to a cupboard of some sort."
}
```
and
```json
{
    "id": "oldCupboard1",
    "scene": "Lighthouse",
    "lock_state": "locked",
    "actions": {
        "look": "This appears to be an old cupboard.",
        "open": {
            "lock_state=locked": "The door won't budge, it is locked tight.",
            "lock_state=unlocked": "You open the door of the cupboard and reveal a list of 5 things which are inside. Number 2 will SHOCK you!"
        }
    },
    "conditions": {
        "keyCupboard1": {
            "action": "use",
            "target": "oldCupboard1",
            "attribute_change": {
                "target": "oldCupboard1",
                "attribute": "lock_state",
                "value": "unlocked"
            },
            "message": "The key fits and the door now appears to be unlocked"
        }
    }
}
```

**Comment by Zet237** [comment]
It looks good to me, we'll have to see how it feels to work with those.
